
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: boaterfly
  password: boaterfly

development:
  <<: *default
  database: directstreams_development

test:
  <<: *default
  database: directstreams_test


production:
  adapter: postgresql
  host: ec2-54-217-202-108.eu-west-1.compute.amazonaws.com
  encoding: unicode
  pool: 5
  username: ylnrcksricjxls
  password: TW8i_aFkwJjpGyJUqr75BurEdi
  database: damddf7qf7sj5q
