
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: boaterfly
  password: boaterfly

development:
  <<: *default
  database: directstreams_development

test:
  <<: *default
  database: directstreams_test


production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: boaterfly
  password: <%= ENV['DIRECTSTREAMS_DATABASE_PASSWORD'] %>
  database: directstreams_test
